Vagrant.configure(2) do |config|
	
	config.vm.box = "centos/stream8"
	config.vm.box_version = "20210210.0"

	config.vm.provision "shell", inline: <<-SHELL
	  yum update -y
	  yum install -y net-tools
	SHELL

	config.vm.define "dbergerS" do |control|
		control.vm.hostname = "dbergerS"
		control.vm.network "private_network", ip: "192.168.56.10"
		control.vm.provider "virtualbox" do |v|
			v.customize ["modifyvm", :id, "--name", "dbergerS"]
			v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
			v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
			v.memory = 512
			v.cpus = 1
		end
		control.vm.provision "shell", path: "scripts/installS.sh"
	end

	config.vm.define "dbergerSW" do |control|
		control.vm.hostname = "dbergerSW"
		control.vm.network "private_network", ip: "192.168.56.11"
		control.vm.provider "virtualbox" do |v|
			v.customize ["modifyvm", :id, "--name", "dbergerSW"]
			v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
			v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
			v.memory = 512
			v.cpus = 1
		end
		control.vm.provision "shell", path: "scripts/installSW.sh"
	end
end